# Generated by Django 4.0.6 on 2022-07-10 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_user_name_comments_user_name_alter_bids_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
