# Generated by Django 4.0.6 on 2022-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_date_listings_status_watchlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
