# Generated by Django 4.0.6 on 2022-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highest_bidder',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
