# Generated by Django 4.0.6 on 2022-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listings_highest_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='highest_bidder',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
