# Generated by Django 4.0.6 on 2022-07-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listings_highest_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='highest_bidder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
