# Generated by Django 4.0.6 on 2022-07-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('0', 'Electronics'), ('1', 'Fashion'), ('2', 'Home Appliance'), ('3', 'Sports'), ('4', 'Toys and Baby Products'), ('5', 'Digital Goods'), ('6', 'Food and Beverages'), ('7', 'Stationary'), ('8', 'Bags and Accecories'), ('9', 'Books'), ('10', 'Vehicles'), ('11', 'Others')], max_length=64),
        ),
    ]
